# Generated by Django 4.0.4 on 2022-04-26 10:29

import apps.gallery.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('minimum_bid_price', models.IntegerField()),
                ('auction_end', models.DateTimeField()),
                ('is_bidable', models.BooleanField(default=False)),
                ('biders', models.JSONField(default=apps.gallery.models.biders_default, verbose_name='BiderData')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
